import Head from 'next/head';
import AccordionList from '../components/TabsList';
import CardList from '../components/Hero/CardList';
import Hero from '../components/Hero/Hero';
import TabsList from '../components/TabsList';

export default function Home() {
  const cardsData = {
    title: '¿Cómo lo hacemos realidad?',
    description:
      'Nuestro modelo de riesgos evalúa en segundos una operación, lo que nos permite financiar en el mismo día.',
    cards: [
      {
        title: 'Financiamiento Directo',
        description:
          'Pensado en empresas que necesiten financiar sus cuentas por cobrar o una alternativa al factoring.',
        link: '#',
        image: '/card-1.png',
      },
      {
        title: 'Pronto Pago',
        description:
          'Similar al Financiamiento Directo pero sin retención, sin costos adicionales por mora y por el 100% de tu factura.',
        link: '#',
        image: '/card-2.png',
      },
      {
        title: 'Crédito de capital',
        description:
          'Para aquellos que buscan potenciar su negocio financiando ordenes de compra o inversión en crecimiento. ',
        link: '#',
        image: '/card-3.png',
      },
      {
        title: 'Confirming',
        description:
          'Pensado para Grandes Empresas y Corporativos que necesiten extender el plazo de sus cuentas por pagar.',
        link: '#',
        image: '/card-4.png',
      },
    ],
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title="Financia el sueño de tu empresa"
        description="Nuestro modelo de riesgos evalúa en segundos una operación, lo que nos permite financiar en el mismo día."
        link="#"
        image="/hero.png"
      />
      <CardList
        title={cardsData.title}
        description={cardsData.description}
        cards={cardsData.cards}
      />
      <TabsList />
    </div>
  );
}
